FROM alpine:3.18.4
RUN apk add --no-cache openssl nmap nmap-nping nmap-ncat nmap-scripts heimdal netcat-openbsd tcpdump ca-certificates curl bash bind-tools jq w3m openssh-client openssh-server iptraf-ng kafkacat
