FROM alpine:3.20.0
RUN apk add --no-cache openssl nmap nmap-nping nmap-ncat nmap-scripts netcat-openbsd tcpdump ca-certificates curl bash bind-tools jq w3m openssh-client openssh-server iptraf-ng rsync
